### ISSUE TITLE
User can time themselves solving a puzzle

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#1]
## 💰 Feature

User can time themselves solving a puzzle

## 🗒️ Notes

Will need to create page structure/styling including header w/ logo icon and nav button, and main page content with timer button and yellow styled div that will contain session data later. Timer button will use React state to govern running/not running and style accordingly.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/25261584/102923398-e8de0600-444c-11eb-9fe3-0aaa187394ab.png)

## ✅ Tasks

- [x] Clone repo
- [x] use npm install to intall all dependencies and dev dependencies
- [x] npm install react-bootstrap bootstrap
- [x] Replace existing title icon with cube icon
- [x] Create timer-page.jsx page in client/pages directory
- [x] Create client/components directory and create header.jsx, timer.jsx, and yellow-section.jsx
- [x] Add logo image to public directory
- [x] Create empty TimerPage component in timer-page.jsx. Import and render TimerPage component in App
- [x] Build Header component in header.jsx using react-bootstrap. Import and render Header component in TimerPage
- [x] Add button react component to TimerPage beneath header, with text "Virtual Cube" (nonfunctional for now)
- [x] Build Timer component in timer.jsx:
   - [x] Initial state will contain properties: running: false, elapsed: 0
   - [x] define methods startTimer() and stopTimer(), and when timer button is clicked and released, if (!this.state.running) call startTimer(), else call stopTimer()
   - [x] startTimer() sets running property of state to true and elapsed to 0, stopTimer() sets running to false
   - [x] in startTimer(), create interval to add 10 to elapsed in state every 10 ms, and in stopTimer() clear interval
   - [x] In render method, display styling and elapsed time (calculated from minutes down to hundreths of a second) based on state
- [x] Import and render Timer component in TimerPage
- [x] Build YellowSection component in yellow-section.jsx with top border-radius styling per figma design. Import and render YellowSection component in TimerPage
