### ISSUE TITLE
User can view WCA world records

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#10]
## 💰 Feature

User can view WCA world records

## 🗒️ Notes

Web scraping with Cheerio

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/25261584/103697407-bf48d280-4f54-11eb-9f14-814ccd3128d1.png)

## ✅ Tasks

- [x] Create new component WorldRecordsPage in pages.
- [x] Add to renderPage() hash routing function in App
- [x] Build page structure and styling using dummy data
- [x] Initialize state with records property set to null
- [x] npm install cheerio
- [x] In db schema, add table "worldRecordsData" with columns "json" and "dateUpdated"
- [x] Create new file 'update-world-records.js' in server: 
   - [x] make fetch request to WCA URL, then call .text() method on response
   - [x] then call cheerio load() method on body, assigning to const $
   - [x] Use cheerio to get necessary text from HTML, trim as necessary, and assemble records array
   - [x] Convert records array to json
   - [x] Create parameterized sql query to delete contents of worldRecordsData table and insert json records array
   - [x] catch and log errors
- [x] In server/index.js, create new get route for getting world records data:
   - [x] Create sql query to select contents of worldRecordsData table
   - [x] query database, send client 200 response with result, catch any errors
- [x] In WorldRecordsPage, create componentDidMount() method and make fetch get request:
   - [x] then parse json response
   - [x] then setState with records array
   - [x] catch and log errors
- [x] Conditionally render loading spinner if state records is null, or page content using records array data
- [x] Conditionally render error text if fetch request fails
- [x] Add World records button to Home component
