### ISSUE TITLE
Modifications: Use spacebar to start/stop timer, scroll to top on hashchange

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#11]
## ✅ Tasks

- [x] In Timer component, create and bind spaceListener() method: 
   - [x] Check if e.code === 'Space'. If so, conditionally start/stop timer based on state.running
   - [x] Prevent default space bar scroll behavior
- [x] Add componentDidMount method, and add 'keydown' event listener to the window, calling spaceListener()
- [x] Add componentWillUnmount method, and remove the event listener
- [x] In App's componentDidMount(), call window.scrollTo(0, 0) to automatically scroll to the top of new page
