### ISSUE TITLE
User can see a list of all solve times for current session

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#2]
## 💰 Feature

User can see all solve times for current session

## 🗒️ Notes

Need to create an array that has each new solve time pushed into it when the timer is stopped. Needs to be accessible by Timer component and new component that will be rendered within YellowSection component

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/25261584/102923398-e8de0600-444c-11eb-9fe3-0aaa187394ab.png)

## ✅ Tasks

- [x] Style Session section within YellowSection component using dummy data
- [x] In TimerPage, create constructor method and initialize state with an object with property sessionTimes set to an empty array
- [x] create addNewTime() method, which takes an argument of a time in ms, copies the array from state, pushes the new time to the array, then sets state with the new array
- [x] Pass addNewTime method to Timer component as a prop, and call it in the Timer component's stopTimer method, passing in the elapsed time as the argument
- [x] Create lib directory and move getDisplayTime() to a new js file there. Import in Timer component
- [x] Create new component SessionTimes and render in YellowSection
- [x] Pass TimerPage's state sessionTimes array to YellowSection, then SessionTimes as props
- [x] In SessionTimes, call map() on sessionTimes array, calling getDisplayTime() (will need to be imported) and creating a new element with each item in the array, and save to a new variable timesList

Changes

- [x] Reconfigure SessionTimes component to use map array method rather than for loop
- [x] Reconfigure getDisplayTime function with ternary operators
- [x] Reconfigure TimerPage component with concat array method
- [x] Change session-data class CSS width property to "100%"
- [x] Reconfigure CSS styling to use bootstrap flex/margin/spacing/text alignment utility classes where applicable
- [x] Reconfigure CSS to use proper CSS classes rather than selector hierarchies
- [x] Render session data content as child within YellowSection component on TimerPage and remove from YellowSection component definition
