### ISSUE TITLE
User can solve with virtual rubik's cube

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#22]
## 💰 Feature

User can solve with virtual rubik's cube

## 🗒️ Notes

N/A

## ✅ Tasks

- [x] Create new react component VirtualCube
- [x] import virtualcube js module
- [x] In render() method, render virtual cube in div using className "virtualcube"
- [x] Style virtual cube sizing and buttons as needed
- [x] In TimerPage component, add new state property virtualCube, initialized to object with properties active (false) and type ('RubiksCube')
- [x] Conditionally render VirtualCube on new row above Timer component
- [x] Create new "Virtual Cube" Button above rendered cube
- [x] Create and bind method toggleVirtualCube which inverts state.virtualCube.active, and pass to onClick of "Virtual Cube" Button
- [x] If virtualCube is rendered, render "Change Type" Button alongside "Virtual Cube" Button
- [x] Create and bind new method changeCubeType() and pass to onClick of "Change Type" Button
- [x] In changeCubeType, conditionally set state.virtualCube.type between 'RubiksCube' and 'PocketCube'
- [x] Pass this.state.type to VirtualCube as props
- [x] In VirtualCube, set value of "kind" attribute to type value passed in from props
- [x] Update cube image colors
