### ISSUE TITLE
Modifications: Timer page buttons, Readme

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#25]
## 🗒️ Notes

N/A

## ✅ Tasks

- [x] Add app info and VirtualCube attribution to Readme
- [x] In Home component, change text of "Timer" button to "Solve"
- [x] In TimerPage, when virtual cube is rendered, render a new exit button rather than changing text for the existing one
- [x] Adjust breakpoint  col widths of columns in row with render virtual cube buttons to match virtual cube and timer
- [x] Change app name to CubeCentral on Home Page, in nav bar, and in title of index.html
