### ISSUE TITLE
Revisions: Log In on sign up, change yellow color

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#27]
## ✅ Tasks

- [x] In SignUpForm component's handleSubmit() method, if sign up is successful make another fetch request to log in (as in LogInForm component)
- [x] Will require importing AppContext
- [x] Change background of yellow areas to a yellow with greater contrast
