### ISSUE TITLE
User can see statistics for current session

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#3]
## 💰 Feature

User can see statistics for current session

## 🗒️ Notes

Styling already created, just need to create array algorithms for different statistic types, research/include standard deviation

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/25261584/102923398-e8de0600-444c-11eb-9fe3-0aaa187394ab.png)

## ✅ Tasks

- [x] Create new SessionStats component, import in TimerPage and render as child of YellowSection, passing in sessionTimes from TimerPage's state as a prop
- [x] In SessionStats component render method, create a new array and assign to new const variable statsArray
- [x] In statsArray, for each stat create an object with the properties: name (string), and result (the return of calling a method, which will call getDisplayName() on the result of the necessary algorithm for that statistic, or 'N/A' if there are no session times). Do this for each of the following:
   - [x] Best
   - [x] Worst
   - [x] Average
   - [x] Median
   - [x] Std Deviation
   - [x] Best avg 5
   - [x] Best avg 3 of 5
- [x] Call map on statsArray, returning react components utilizing the name and result for each object, and assign to new const variable statsForRender
- [x] Return the necessary styled react elements with statsForRender from the render method of SessionStats

Changes
- [x] Return directly from ternary expressions in getBest, getWorst, getAverage
- [x] Use short guards in getMedian and getStdDeviation
