### ISSUE TITLE
User can delete a time

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#4]
## 💰 Feature

User can see delete a time

## 🗒️ Notes

Need to add a unique identifier to each rendered time "X" to target the corresponding sessionTimes array index for deletion

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/25261584/102923398-e8de0600-444c-11eb-9fe3-0aaa187394ab.png)

## ✅ Tasks

- [x] In TimerPage, create deleteTime method with parameter "index" and pass this.deleteTime() to SessionTimes component as prop
- [x] Bind this to deleteTime() in TimerPage's constructor
- [x] In deleteTime(), make a  shallow copy of this.state.sessionTimes with slice(), assigned to const variable newSessionTimes
- [x]  Use splice() to remove the element at the index passed in as an argument from newSessionTimes array
- [x] setState() with newSessionTimes as the value of sessionTimes
- [x] Add data-time-index attribute to each i element rendered in SessionTimes, with a value of i (the current index in map)
- [x] In SessionTimes, create deleteTimeByIndex method with parameter "e" and bind this in constructor
- [x] In deleteTimeByIndex(), extract the numerical value of the event target's data-time-index attribute, and call this.props.deleteTime, passing the data-time-index as an argument
- [x] Add onClick attribute to each i element with value of this.deleteTimeByIndex()
