### ISSUE TITLE
User can reset the timing session

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#5]
## 💰 Feature

User can see reset the timing session

## 🗒️ Notes

N/A

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/25261584/102923398-e8de0600-444c-11eb-9fe3-0aaa187394ab.png)

## ✅ Tasks

- [x] In TimerPage, render new bootstrap Button component for Reset Session within YellowSection
- [x] Create react-bootstrap modal in render method (Are you sure you want to reset session?...)
- [x] Add showResetModal property to state, initialized to false.
- [x] Add show attribute to Modal component, with value this.state.showResetModal
- [x] Create new method toggleResetModal, and bind this
- [x] In toggleResetModal, setState() with the inverse of the current value of this.state.showResetModal
- [x] Create new method resetSession, and bind this
- [x] in resetSession(), set value of sessionTimes in state to an empty array and set showResetModal to false using setState()
- [x] Add toggleResetModal() as an onClick attribute for the Reset Session button in YellowSection, the Cancel button in the modal, and an onHide attribute for the modal
- [x] Add resetSession() as an onClick attribute for the Reset Session button in the modal
