### ISSUE TITLE
User can create a profile

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#6]
## 💰 Feature

User can create a profile

## 🗒️ Notes

Profile creation, not log in. Restructure App component, implement hash routing, set up database, and make fetch requests to server

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/25261584/103313087-d9723600-49d3-11eb-8e1d-454ddbf85d6b.png)

## ✅ Tasks

- [x] Create new file login-signup.jsx in pages, and create new component LogInSignUp
- [x] Create parseRoute function in new module in library, and import in app.jsx
- [x] In app.jsx, create constructor with state route property set to parseRoute(window.location.hash)
   - [x] Create componentDidMount method, and listen for hashchange events, setting state with the new route
   - [x] Create renderPage method, rendering either TimerPage or LogInSignUp depending on route in state
   - [x] Call renderPage() in render function to determine what page is rendered
- [x] Build out new Sign Up page with sign up form per figma design above, substituting Sign Up info for Log In info
- [x] Start postgresql and create new db with createdb speedCubeTimer
- [x] Export SQL from dbdesigner and add to database/schema.sql
- [x] Import the db schema with npm run db:import and inspect with pgweb --db=speedCubeTimer
- [x] In server/index.js, use json middleware
- [x] Create post route which does the following:
   - [x] verify username and password were provided in req.body/throws 400 error
   - [x] Password 8 character minimum validation
   - [x] hash password with argon2, then make parameterized sql query to insert username and hashed password into users table and return select user data
   - [x] query database, then respond with 201 and json containing returned user data
   - [x] catch any errors
- [x] In LogInSignUp, create a new method that is called onSubmit of form:
   - [x] make a fetch request to the post route that was created earlier, with the username and password in the request body
   - [x] then, reset the form
   - [x] catch any errors
- [x] Make username and password required fields
- [x] Add status property to state, initialized to empty string
- [x] Add p tag just below form, with text content from this.state.status, and update status based on results of fetch request
