### ISSUE TITLE
User can log in/out of their account

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#7]
## 💰 Feature

User can log in/out of their account

## 🗒️ Notes

Build home page (default when not logged in), profile page (default when logged in), and log in page similar to sign up page. Handle authentication using token and context. Customize nav bar options based on signed in status

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/25261584/103377418-37665280-4a94-11eb-8b10-3436b7a7114f.png)

## ✅ Tasks

- [x] Build Home page on home.jsx per figma design (leave out World Records for now), linking buttons to applicable hash routes
- [x] Build Profile page structure in new file pages/profile.jsx per figma design, leaving out My Records data for now
- [x] Build LogInForm component per figma design, using SignUpForm as template
- [x] Add links to LogInForm and SignUpForm to link between each other (changing hash routes)
- [x] In LogInSignUpPage, render either LogInForm or SignUpForm depending on hash route
- [x] In App, add state user property initialized to null
- [x] Create lib/app-context.js module, createContext() assigned to const AppContext, export default, and import in app.jsx
- [x] In App's render method, assign an object with user property set to this.state.user to const contextValue
- [x] Wrap returned components in render method in AppContext.Provider with attribute value={contextValue}
- [x] Create handleSignIn method with one parameter: result, and bind this
   - [x] destructure user and token from result object
   - [x] add token to window.localStorage with setItem()
   - [x] setState() with user
   - [x] Change hash to empty to redirect to profile page
   - [x] add handleLogIn as a property in contextValue object
- [x] In App's renderPage function, when route path is an empty string, render Home if state user property is null, else render Profile
- [x] In index.js, create post route to handle Sign In requests:
   - [x] Destructure username and password from the req.body, and if either has not been provided throw 401 ClientError
   - [x] Create parameterized sql to select userId and hashedPassword from users table where username is the provided username
   - [x] query the database, then destructure the first element of the result.rows array and assign to const variable userInfo
   - [x] If userInfo is falsy throw a 401 ClientError
   - [x] destructure the userId and hashedPassword from userInfo, and return argon2, calling verify method with the hashedPassword and provided password to compare
   - [x] then, if they are not matching throw a 401 ClientError
   - [x] assemble a payload object with the userId and username, and call jwt.sign() with the payload and process.env.TOKEN_SECRET) as arguments, assigning to const token
   - [x] send json response with the token and payload
   - [x] catch errors
- [x] Change token secret in .env
- [x] In LogInForm component, import AppContext
- [x] Create handleSubmit method and pass to onSubmit event for the form
   - [x] event.preventDefault()
   - [x] Make a fetch request to the log-in post route, with json for the entered username and password in the request body
   - [x] .then parse json
   - [x] .then if result contains user and token, call App's handleLogIn function (via context) with argument (result)
   - [x] in the case of an error, setState so status property displays the error message
- [x] Include joinDate in sql and add to payload for log-in post request
- [x] Pass username and joinDate to applicable field in Profile component via context
- [x] In App, create handleLogOut method and bind this
   - [x] Remove token from window.localStorage with removeItem()
   - [x] setState user to null
   - [x] add handleLogOut as a property in contextValue object
- [x] In Header, import AppContext and use ternary expressions to render welcome message, Profile option, Log In/Sign Up button or Log Out button based on context user status
- [x] For Log Out button, click event fires handleLogOut function via context
- [x] In App's componentDidMount(), get token from localStorage, decode, and set state
