### ISSUE TITLE
User can save personal records

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#8]
## 💰 Feature

User can save personal records

## 🗒️ Notes

When logged in, add button on timer page to Save Record, select which puzzle type and record type, and save to database.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/25261584/103422749-d1db9a00-4b57-11eb-803d-55f141e984e4.png)

## ✅ Tasks

- [x] Import AppContext in timer-page module
- [x] Conditionally render Save Record button if user is logged in
- [x] In TimerPage, add property sessionRecords to this.state, initialized to null
- [x] Create and bind new method getSessionRecords:
   - [x] use algorithm to get best time and best avg 3 of 5
   - [x] package best time, best avg, and an array of the 5 times that make up the best 3 of 5 into an object and return that object
- [x] In addNewTime() and deleteTime(), call getSessionRecords() and include updates to sessionRecords in setState()
- [x] In resetSession's setState, set sessionRecords to null
- [x] Add authorization middleware module to server directory, import and use in index.js after existing post routes
- [x] Beneath the authorization middleware, create a new post route for submitting a new record:
   - [x] deconstruct the userId from req.user (created in authorization middleware)
   - [x] deconstruct puzzleTypeId, recordTypeId, and solves from req.body, throw 400 ClientError if values are falsy
   - [x] declare const newRecordSql and insert into records table: userId, puzzleTypeId, recordTypeId, and recordDate (with now() ), returning recordId via parameterized query
   - [x] db query, then deconstruct recordId from result.rows
   - [x] declare const solvesSql and use pg-format (npm install pg-format) to create dynamic sql query inserting into solves: recordId, and time (via solves array)
   - [x] db query, then send 201 response to client
   - [x] catch any errors
- [x] In data.sql, add necessary puzzleTypes and recordTypes, and import into database
- [x] Create new component saveRecordModal
   - [x] Modal contains form with 2 select fields: puzzle type and record type, changes update corresponding state properties
   - [x] Display selected record time via state in modal.
   - [x] Buttons for Submit New Record and Cancel
- [x] In TimerPage, render saveRecordModal, add property showSaveRecordModal to state, create and bind method toggleSaveRecordModal, and toggle 'show' modal via onClick of Save Record button
- [x] Pass sessionRecords state property to saveRecordModal
- [x] In saveRecordModal component, create and bind new function saveNewRecord with parameter: event
   - [x] assign either bestSingle or bestAverage3Of5Arr value to a new variable 'solves' based on value of recordTypeId
   - [x] Make fetch  post request with 'x-access-token' in req.headers, and puzzleTypeId, recordTypeId, and solves array in req.body
   - [x] Set a state status property that is updated with the success/failure of the fetch request
- [x] Conditionally render modal content based on state 'status' property. Initialized to null.
   - [x] Displays 'Record successfully saved' with Close button if fetch success. Close also reset state status back to null
   - [x] Displays error if error
- [x] Call saveNewRecord() onSubmit of modal form
