### ISSUE TITLE
User can view personal records on profile

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/cube-central#9]
## 💰 Feature

User can view personal records on profile

## 🗒️ Notes

DB query. When average times are displayed, show all 5 times with parentheses around the 3 used for the average

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/25261584/103593844-c9fb5d00-4eab-11eb-89f1-c24261d311f7.png)

## ✅ Tasks

- [x] Create new component MyRecords, and render in Profile component as a child of YellowSection
- [x] In MyRecords, add state property "puzzleType", initialized to '3x3x3 Cube'.
- [x] Add state property "records", initialized to object with properties "bestSingle" and "bestAverage3Of5Arr", both initialized to null
- [x] Build MyRecords structure and styling, including form with select field. Assign this.state.puzzleType as "value" attribute to form select field.
- [x] Create and bind handleChange method which updates state puzzleType for form select field's onChange
- [x] Use getDisplayTime imported function to display times
- [x] Create a new function to properly display all 5 times for average
- [x] In index.js, create new get route for records:
   - [x] deconstruct userId from req.user obj
   - [x] deconstruct puzzleType from req.body object
   - [x] throw 400 ClientError if !puzzleType
   - [x] create parameterized sql query to select "time" from table "solves" and "label" from table "recordTypes" for each of the user's solves for the specified puzzleType. Will need to join all 5 database tables.
   - [x] query database, then assemble returned data into object structured like the records object in MyRecords' state, with time values in arrays, or null
   - [x] send 200 response with records object to client
   - [x] catch any errors
- [x] In MyRecords, create and bind new method getRecords, and call in handleChange() as well as componentDidMount():
   - [x] fetch request with headers: json content-type, and x-access-token (import AppContext), and body: JSON.stringify(this.state.puzzleType)
   - [x] then parse json response
   - [x] then setState with result object assigned to records property
